### ISSUE TITLE
Project does not build in Qt creator on linux, both fully updated.

### ISSUE THREAD

**Issue by grantrostig** [AlanU/signal-slot-timer#2]
Project does not build in Qt creator on linux, both fully updated.  Cmake also.

/home/user1/src/cpp_by_example/signal-slot-timer-main/CMakeLists.txt:6: error: Cannot find source file:

  src/stimer.h

/home/user1/src/cpp_by_example/signal-slot-timer-main/CMakeLists.txt:6: error: No SOURCES given to target: signal_slot_timer

**Comment by AlanU** [comment]
fix pushed an update to cmake it qt creator requires cmake_minimum_required(VERSION 3.5)
